### ISSUE TITLE
AttributeError: 'module' object has no attribute 'abc'

### ISSUE THREAD

**Issue by svenmh** [abw333/dominoes#125] opened 2017-11-01 17:24 UTC
$ ./bin/dominoes 
Traceback (most recent call last):
  File "./bin/dominoes", line 3, in <module>
    import dominoes
  File "/home/sven/Local/lib/python3.4/site-packages/dominoes/__init__.py", line 13, in <module>
    from dominoes.hand import Hand
  File "/home/sven/Local/lib/python3.4/site-packages/dominoes/hand.py", line 18, in <module>
    class Hand(collections.abc.Sequence):
AttributeError: 'module' object has no attribute 'abc'

**Comment by abw333** [comment] 2017-11-01 17:39
Hi, I believe this is happening because this library only supports Python 3.6 and you are using Python 3.4. Can you try upgrading to Python 3.6?

**Comment by svenmh** [comment] 2017-11-01 17:42
OK, I'll try that.  3.4 is the latest that comes prebuilt on CentOS.   I'll get back to you it a bit.

**Comment by svenmh** [comment] 2017-11-01 18:02
I thought I was going to have to build 3.6, but I had a 3.5 version around it works well in that.  So I'm good.  Thanks.

**Comment by abw333** [comment] 2017-11-01 18:09
OK. I only run the tests in 3.6, so it might be worth running them in 3.5 to make sure that everything is actually working correctly. You can run them using `python setup.py test`. I am closing this issue, but feel free to file another one if you run into any more trouble.

**Closed by abw333** 2017-11-01 18:09 UTC

**Comment by AhmadBilal1989** [comment] 2017-11-05 14:40
please tell me if we want to calculate probabilities of the tiles after shuffling and distributing and when each player will put a tile on the board. where to make changings?

**Comment by AhmadBilal1989** [comment] 2017-11-05 14:40
i am stuck for my project. i have to calculate probabilities, i am not sure where to make changings? need serious help please.

**Comment by abw333** [comment] 2017-11-05 14:44
Hi, I am happy to help, but please file a new issue with more details about what you are trying to accomplish. Thanks.

**Comment by abw333** [comment] 2018-10-25 14:09
Hi @FutoRicky, thanks for bringing this up.

I was able to reproduce the issue on Python 3.7, and I know how to fix it. I'll let you know when the fix is up (most likely within the next day or two), but, in the meantime, you can try using Python 3.6.

I created a new issue to track this work: https://github.com/abw333/dominoes/issues/128

**Comment by abw333** [comment] 2018-10-27 20:57
@FutoRicky I merged in a fix for issue #128 to the `master` branch, and published the updated `dominoes` library to PyPI as version `6.1.0`. Let me know if you have any issues upgrading or using the upgraded code.
